// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fttgrdddakwdpojwoeus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dGdyZGRkYWt3ZHBvandvZXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NDUxOTIsImV4cCI6MjA1NTAyMTE5Mn0.EKLPC1kv3KnDYBRUkaErXiCyVFDk9Kh_KygjHGSho5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);